version: '3'

services:
  flaschatdb:
    image: mariadb
    container_name: flaschatdb
    hostname: flaschatdb
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=0UFX0eHyR4iLWVM
      - MARIADB_USER=flaschat
      - MARIADB_PASSWORD=h8r9BKbFNvEgYxS
      - MARIADB_DATABASE=message_db
    ports:
      - "3306:3306"

  flaschatphpmyadmin:
    image: phpmyadmin
    container_name: flaschatphpmyadmin
    hostname: flaschatphpmyadmin
    depends_on:
      - flaschatdb
    restart: unless-stopped
    ports:
      - 5878:80
    environment:
      - PMA_ARBITRARY=1